name: Deploy to Modal

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5   

    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      MODAL_CONFIG_DIR: /home/runner/.modal  # 强制写入 Modal CLI 配置目录

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Modal SDK
        run: pip install --no-cache-dir --upgrade "modal>=0.58.0"

      - name: Check Modal version
        run: python -c "import modal; print(modal.__version__)"

      - name: Inject Modal Token
        run: |
          mkdir -p $MODAL_CONFIG_DIR
          echo -e "[default]" > $MODAL_CONFIG_DIR/token.toml
          echo -e "token_id = \"$MODAL_TOKEN_ID\"" >> $MODAL_CONFIG_DIR/token.toml
          echo -e "token_secret = \"$MODAL_TOKEN_SECRET\"" >> $MODAL_CONFIG_DIR/token.toml
          

      - name: Run app remotely
        run: python deploy.py
